# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# Block Designs: bd/EES_351/EES_351.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351 || ORIG_REF_NAME==EES_351} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_processing_system7_0_0/EES_351_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_processing_system7_0_0 || ORIG_REF_NAME==EES_351_processing_system7_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==EES_351_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_v_tc_0_0/EES_351_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_v_tc_0_0 || ORIG_REF_NAME==EES_351_v_tc_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_v_vid_in_axi4s_0_0/EES_351_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==EES_351_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_OV_Sensor_ML_0_0/EES_351_OV_Sensor_ML_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_OV_Sensor_ML_0_0 || ORIG_REF_NAME==EES_351_OV_Sensor_ML_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_clk_wiz_0_0/EES_351_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_clk_wiz_0_0 || ORIG_REF_NAME==EES_351_clk_wiz_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_xlslice_0_0/EES_351_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_xlslice_0_0 || ORIG_REF_NAME==EES_351_xlslice_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_xlconcat_0_0/EES_351_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_xlconcat_0_0 || ORIG_REF_NAME==EES_351_xlconcat_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_axi_vdma_0_0/EES_351_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_axi_vdma_0_0 || ORIG_REF_NAME==EES_351_axi_vdma_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_axi_gpio_0_0/EES_351_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_axi_gpio_0_0 || ORIG_REF_NAME==EES_351_axi_gpio_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_axi_smc_0/EES_351_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_axi_smc_0 || ORIG_REF_NAME==EES_351_axi_smc_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_rst_ps7_0_100M_0/EES_351_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_rst_ps7_0_100M_0 || ORIG_REF_NAME==EES_351_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_xlslice_0_1/EES_351_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_xlslice_0_1 || ORIG_REF_NAME==EES_351_xlslice_0_1} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_xlslice_0_2/EES_351_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_xlslice_0_2 || ORIG_REF_NAME==EES_351_xlslice_0_2} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_util_vector_logic_0_1/EES_351_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_util_vector_logic_0_1 || ORIG_REF_NAME==EES_351_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_util_vector_logic_0_2/EES_351_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_util_vector_logic_0_2 || ORIG_REF_NAME==EES_351_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_clk_wiz_1_0/EES_351_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_clk_wiz_1_0 || ORIG_REF_NAME==EES_351_clk_wiz_1_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_proc_sys_reset_0_0/EES_351_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_proc_sys_reset_0_0 || ORIG_REF_NAME==EES_351_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_proc_sys_reset_0_1/EES_351_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_proc_sys_reset_0_1 || ORIG_REF_NAME==EES_351_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_proc_sys_reset_0_2/EES_351_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_proc_sys_reset_0_2 || ORIG_REF_NAME==EES_351_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_xbar_1/EES_351_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_xbar_1 || ORIG_REF_NAME==EES_351_xbar_1} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_ps7_0_axi_periph_1/EES_351_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_ps7_0_axi_periph_1 || ORIG_REF_NAME==EES_351_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_util_vector_logic_1_0/EES_351_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_util_vector_logic_1_0 || ORIG_REF_NAME==EES_351_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_video_0_0/EES_351_video_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_video_0_0 || ORIG_REF_NAME==EES_351_video_0_0} -quiet] -quiet

# IP: bd/EES_351/ip/EES_351_auto_pc_0/EES_351_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EES_351_auto_pc_0 || ORIG_REF_NAME==EES_351_auto_pc_0} -quiet] -quiet

# XDC: bd/EES_351/EES_351_ooc.xdc
