# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0.xci
# IP: The module: 'EES_351_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_351_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_351_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0.xci
# IP: The module: 'EES_351_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_351_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Eureka/Desktop/EES_351/EES_351.srcs/sources_1/bd/EES_351/ip/EES_351_v_axi4s_vid_out_0_0/EES_351_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EES_351_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
